[package]
name = "lexer"
version = "0.3.0"
edition = "2024"
description = "A simple Lexer builder without magic."

[dependencies]
bit-set       = { version = "0.8.0"                                  }
imstr         = { version = "0.2.0"                                  }
proptest      = { version = "1.9.0", features = [ "proptest-macro" ] }

[lints.rust]
non_snake_case = "allow"
nonstandard_style = "allow"

[lints.clippy]
needless_arbitrary_self_type = "allow"
needless_return = "allow"
